services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "events"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: